"""Add updated_at column to products

Revision ID: 341a5726c3c0
Revises: 2d9bcfa27de5
Create Date: 2025-11-12 16:01:04.126047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341a5726c3c0'
down_revision = '2d9bcfa27de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
